### ISSUE TITLE
Người việt huh ? :v 

### ISSUE THREAD

**Issue by dinhduynhat** [mrvir/Chaos#4]

**Comment by lehuukhoa** [comment]
người việt đó

**Comment by dinhduynhat** [comment]
Hợp tác làm server này nọ không chú :v agarvn.com ( check server em xem :v )

**Comment by mrvir** [comment]
không nha bạn, mình có rất ít thời gian

**Comment by dinhduynhat** [comment]
:v oh kcj

**Comment by lehuukhoa** [comment]
This code của bạn 
Mình sử dụng code bạn phát triển lên nhé

**Comment by lehuukhoa** [comment]
Tks
